project_id = "jczffinsulwdzhgzggcj"
[functions.api-upload-trace]
enabled = true
verify_jwt = true
import_map = "./functions/api-upload-trace/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/api-upload-trace/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/api-upload-trace/*.html" ]
