// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jczffinsulwdzhgzggcj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjemZmaW5zdWx3ZHpoZ3pnZ2NqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMjA5NzAsImV4cCI6MjA2MDY5Njk3MH0.IU-c2KErSX6q-rce67ZMdJzI2Xk_my_1OUq5u4S95lE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);